id = "vscode-icons"
name = "VSCode Icons Theme"
version = "0.2.0"
schema_version = 1
authors = ["Pranav Mangal <pranav.mangal.7@gmail.com>"]
description = "VSCode icons theme for Zed"
repository = "https://github.com/pranavmangal/zed-vscode-icons"
